name: restaurant-recommend-classifier
channels:
    - anaconda
    - conda-forge
    - defaults
    - conda-forge
dependencies:
    - bokeh
    - jupyterlab
    - pandas
    - python
    - scikit-learn
    - scikit-plot
    - seaborn
    - pip
    - requests
    - pillow
    - pip:
          - python-dotenv
          - torch
          - torchvision
          - torchaudio
          - --index-url=https://download.pytorch.org/whl/cu118 # this needs to be allways at the end
