name: restaurant-recommend-classifier
channels:
    - anaconda
    - conda-forge
    - defaults
dependencies:
    - bokeh
    - jupyterlab
    - pandas
    - python
    - scikit-learn
    - scikit-plot
    - seaborn
    - geopy
    - numpy<2.0
    - opencv # kompatible with numpy<2.0
    - pip
    - requests
    - pillow
    - tqdm
    - pytest
    - streamlit
    - surprise
    - tldextract
    - imagehash
    - streamlit
    - pip:
          - python-dotenv
          - ddgs
          - --extra-index-url=https://download.pytorch.org/whl/cu118
          - torch
          - torchvision
          - torchaudio
          - surprise
