food_to_cuisines = {
    "Grilled beef tongue": ["japanese", "korean"],
    "Flavored snail meat": ["chinese", "vietnamese"],
    "Napoleon cake": ["french", "russian"],
    "Spicy chicken": ["chinese", "thai", "indian"],
    "Noodles with pork chop": ["chinese", "taiwanese"],
    "Stir-fried pork with capers": ["chinese"],
    "Bang bang chicken": ["chinese"],
    "Hibiscus crab stick": ["japanese"],
    "Tomato and egg flour pimple soup": ["chinese"],
    "Grilled ribs": ["american", "korean", "brazilian"],
    "Stir-fried lettuce": ["chinese"],
    "Stir-fried clams with chili sauce": ["chinese", "thai"],
    "Brownie": ["american"],
    "Duck feet": ["chinese"],
    "Hand cake": ["taiwanese", "chinese"],
    "Durian pancake": ["malaysian", "indonesian", "thai"],
    "Griddle rabbit": ["chinese"],
    "Dried chiba bean curd": ["chinese"],
    "Plate reinforcement": ["chinese"],  # unclear name; assumed Chinese -gpt
    "Tobiko warship sushi": ["japanese"],
    "Meringue puffs": ["french"],
    "Fried pork with sauerkraut": ["german", "austrian"],
    "Potato salad": ["american", "german", "russian"],
    "Onion mixed fungus": ["chinese"],
    "Crepe": ["french"],
    "Crispy chicken bibimbap": ["korean"],
    "Golden cake": ["chinese"],
    "Bean sprouts in soup": ["korean", "vietnamese", "chinese"],
    "Steamed fish head with double pepper": ["chinese"],
    "Mung bean soup": ["chinese", "korean"],
    "Good harvest of coarse grains": ["chinese"],  # assumed regional name -gpt
    "Crab fried rice cake": ["korean", "chinese"],
    "Chicken casserole": ["british", "american"],
    "Pan-fried three stuffed treasures": ["chinese"],
    "Firewood chicken": ["chinese"],
    "Golden cod": ["chinese", "british"],
    "Waxiang chicken": ["chinese"],
    "Corn with pine nuts": ["chinese"],
    "Secret jujube": ["chinese"],
    "Pork with preserved vegetable": ["chinese"],
    "Fried hairtail": ["chinese"],
    "Yogurt purple rice": ["korean", "chinese"],
    "Home-style bean curd": ["chinese"],
    "Double chicken drumsticks": ["american", "chinese"],
    "Fried crab with curry": ["thai", "malaysian", "indian"],
    "Fried cantonese sausage": ["chinese"],
    "Roasted eggplant with garlic": ["mediterranean", "greek", "turkish"],  # but trimmed to "greek", "turkish" -gpt
    "Shrimp skewers": ["greek", "brazilian", "japanese"],
    "Wonton noodles": ["chinese"],
    "Fried kidney flower with pig liver": ["chinese"],
    "Vinegar cabbage": ["german", "chinese"],
    "Crab roe salad": ["japanese", "chinese"],
    "Fried eggplant": ["turkish", "italian", "indian"],
    "Four red porridge": ["gambian"],  # probably gambian
    "Boiled fish": ["chinese"],
    "Grilled chicken feet": ["chinese"],
    "Roast eggplants": ["greek", "turkish"],
    "Kidney beans": ["mexican", "indian", "brazilian"],
    "Straw hat cake": ["chinese"],  # from one piece(?), no joke look it up
    "Meicai bamboo shoots": ["chinese"],
    "Cold pork cold head": ["chinese"],
    "Braised duck gizzards": ["chinese"],
    "Wasabi octopus": ["japanese"],
    "Cheese baked sweet potatoes": ["american", "japanese"],
    "Fried twist": ["chinese"],
    "Dumplings": ["chinese", "russian", "polish", "japanese", "korean"],
    "Tomato pasta": ["italian"],
    "Dried carob": ["middle eastern", "turkish"],  # use "turkish" -gpt
    "Toffee cake": ["british"],
    "Crab yellow tofu": ["chinese"],
    "Barbecue ribs": ["american", "korean", "chinese"],
    "Strawberry sundae": ["american"],
    "Pineapple rice": ["thai"],
    "Tin foil potatoes": ["american"],
    "Stir-fried pork with rice white": ["korean"],  # check this one again
    "Black pepper pork chop rice": ["chinese", "singaporean"],
    "Ribs rice": ["chinese"],
    "Braised noodles with ribs": ["chinese"],
    "Spicy shrimp": ["thai", "chinese"],
    "Choy sum with garlic sauce": ["chinese"],
    "Steamed chicken in lotus leaves": ["chinese"],
    "Spicy cabbage fried rice": ["korean", "chinese"],
    "Pineapple fritters shrimp": ["thai"],
    "Spicy shao pointed": ["chinese"],
    "Scallion lamb": ["chinese"],
    "Bazhen tofu": ["chinese"],
    "Donkey meat": ["chinese"],
    "Fried egg roll": ["chinese", "american"],
    "Gourd head bread in the soup": ["chinese"],  # assumed -gpt
    "Fish head tofu soup": ["chinese"],
    "Fried spring rolls with three pieces of silk": ["chinese"],
    "Braised beef brisket on rice": ["chinese"],
    "Smoked fish": ["russian", "swedish", "japanese"],
    "Fried rice noodles with eggs": ["chinese", "singaporean"],
    "Corn ribs soup": ["chinese"],
    "Rib skewers": ["chinese", "turkish"],
    "Fried shao mai": ["chinese"],
    "Shredded potatoes with salad": ["german", "chinese"],
    "Glutinous rice balls with peanuts and sesame seed": ["chinese"],
    "Fried potato chips with spicy cabbage": ["korean", "chinese"],
    "Crab stick nigiri sushi": ["japanese"],
    "Steamed pumpkin with red dates": ["chinese"],
    "Coconut jelly": ["thai", "vietnamese"],  # common SE Asian dessert -gpt
    "Fried edamame with pickled vegetables": ["japanese", "chinese"],
    "Braised pork on rice": ["taiwanese", "chinese"],
    "Braised chicken nuggets": ["chinese"],
    "Preserved egg with hot pepper": ["chinese"],
    "Green tea cake": ["japanese", "chinese"],
    "White rice": ["chinese", "japanese", "korean"],
    "Pork liver noodle": ["chinese"],
    "Spicy fish": ["chinese", "thai"],
    "Sauerkraut beef": ["chinese", "german"],  # depends on context; likely chinese here -gpt
    "Lotus pond side dishes": ["chinese"],  # name suggests traditional Chinese sides -gpt
    "Green pepper stir-fried dregs": ["chinese"],  # assumed regional stir-fry -gpt
    "Fried bacon with bamboo shoots": ["chinese"],
    "Grilled prawns": ["thai", "brazilian", "chinese"],
    "Grilled duck intestine skewers": ["chinese"],
    "Stir-fried beef fillet with tea mushroom": ["chinese"],
    "Scrambled noodles with tomato and egg": ["chinese"],
    "Snowflake chicken fillet": ["chinese"],  # likely a creative dish name -gpt
    "Refreshing evergreen": ["chinese"],  # unclear, assumed Chinese cold dish -gpt
    "Fried chicken gizzards": ["chinese", "filipino", "american"],
    "Scallion sea bass": ["chinese"],
    "Red date and yam congee": ["chinese"],
    "Coarse grain porridge": ["chinese"],
    "Stewed chicken nuggets": ["chinese"],
    "Spicy pork": ["korean", "chinese"],
    "Pickled mustard": ["chinese"],
    "Matcha mousse cake": ["japanese"],
    "Snowflake cowboy bones": ["chinese"],  # creative name, likely ribs -gpt
    "Fried flower beetle": ["chinese"],  # edible insect cuisine, common in parts of China -gpt
    "Roast pork": ["chinese", "filipino", "american"],
    "Flamingo cake": ["chinese"],  # novelty dessert name, likely Chinese bakery -gpt
    "Colorful face lift": ["chinese"],  # assumed plated cold dish -gpt
    "Cool coconut milk": ["thai", "vietnamese"],
    "Tossed fish skin": ["chinese"],
    "Sparerib noodles": ["chinese"],
    "Boneless chicken feet": ["chinese"],
    "Pork sauerkraut bun": ["chinese"],
    "Soy milk": ["chinese", "korean"],
    "Beef brisket noodle": ["chinese"],
    "Five recipes of tender beef": ["chinese"],  # assumed variety platter -gpt
    "Fried pork with pleurotus eryngii": ["chinese"],
    "Griddle chicken": ["chinese"],
    "Red bean curd": ["chinese"],
    "Custard bun": ["chinese"],
    "Fried lotus white with oil residue": ["chinese"],  # lotus stem dish -gpt
    "Kimchi beef sushi": ["korean", "japanese"],
    "Red bean double skin milk": ["chinese"],
    "Mutton soup": ["chinese", "central_african"],  # but central_african unlikely—chinese here -gpt
    "Fire bun": ["chinese"],  # likely spicy meat bun -gpt
    "Beef and rice noodle soup": ["vietnamese", "chinese"],
    "Fried mushrooms": ["chinese", "japanese", "italian"],
    "Stir-fried shredded pork with garlic moss": ["chinese"],
    "Smooth double skin milk": ["chinese"],
    "Soy bean curd": ["chinese"],
    "Beef claypot rice": ["chinese"],
    "Fried chicken chop": ["taiwanese", "chinese"],
    "Refreshing lotus root slices": ["chinese"],
    "Fried shredded pancake": ["chinese"],
    "Hot pot noodles": ["chinese"],
    "Fried pork with chili": ["chinese"],
    "Saute spicy chicken": ["chinese"],
    "Pork with preserved vegetable rice": ["chinese"],
    "Tiramisu cake": ["italian"],
    "Soy sauce fish": ["chinese"],
    "Baked potato chips": ["american", "british"],
    "Cream of mushroom soup": ["french", "american"],
    "Baked fairy grass with Taro": ["chinese"],  # herbal dessert, possibly SE Asian but we'll say chinese -gpt
    "Baked corn with egg yolk": ["chinese"],
    "Steam pot chicken": ["chinese"],
    "Tomato and egg soup": ["chinese"],
    "River noodles in pig soup": ["chinese"],
    "Matcha yellow peach cake": ["japanese"],
    "Fruit pizza": ["american"],
    "Sweet plum and sweet potato": ["chinese"],
    "Cucumber preserved egg soup": ["chinese"],
    "Scrambled egg with chopped chili pepper": ["chinese"],
    "Pineapple cake": ["taiwanese"],
    "Fried balls and radish": ["chinese"],  # vague, assumed fritters -gpt
    "Steamed abalone with garlic and vermicelli": ["chinese"],
    "Overlord chicken strips": ["chinese"],  # likely spicy or bold-flavored -gpt
    "Braised chicken": ["chinese"],
    "Three delicacies in casserole": ["chinese"],
    "Crispy corn cob": ["chinese"],
    "Steamed mandarin fish": ["chinese"],
    "Chinese salad": ["chinese"],
    "Hotbed chives with pork": ["chinese"],
    "Clam tofu soup": ["chinese"],
    "Tuna onigiri": ["japanese"],
    "Beef ribs": ["korean", "american", "brazilian"],
    "Spicy cabbage sushi roll": ["korean", "japanese"],
    "Pickled mustard with shredded soup": ["chinese"],
    "Red oil dumplings": ["chinese"],
    "Fried shrimp": ["chinese", "american", "japanese"],
    "Crispy radish skin": ["chinese"],
    "Fried tofu": ["chinese", "japanese", "thai"],
    "Salted chicken": ["chinese"],
    "Baked pig brain with tin foil": ["chinese"],
    "Sour and spicy fish meal with grain": ["chinese"],
    "Enoki mushroom": ["japanese", "chinese"],  # used in hot pot and stir-fry -gpt
    "Lotus root box": ["chinese"],
    "Simmered dry noodles": ["chinese"],  # likely Hubei or Shaanxi style -gpt
    "Pigeon soup": ["chinese"],
    "Duck belly": ["chinese"],  # offal-based dish -gpt
    "Beef jerky": ["american", "south_african"],  # biltong in SA, but most likely american here -gpt
    "Chestnut cream soup": ["french"],
    "Plum kidney bean": ["chinese"],
    "Red bean sago": ["chinese"],
    "Lemon sauerkraut fish": ["chinese"],  # modern fusion, likely Chinese -gpt
    "Sauce chili": ["chinese"],  # chili sauce-based dish -gpt
    "Squid crisp": ["japanese", "chinese"],
    "Spicy korean noodles": ["korean"],
    "Steamed rice with mei cai meatloaf": ["chinese"],
    "King crab": ["japanese", "american", "russian"],  # broadly popular -gpt
    "Beef noodle soup": ["taiwanese", "chinese"],
    "Fried frog": ["chinese", "french", "vietnamese"],
    "Mustard duck feet": ["chinese"],
    "Fried squid": ["japanese", "chinese"],
    "Cucumber with pork ears": ["chinese"],
    "Oily noodles": ["chinese"],
    "Red oil yuba": ["chinese"],
    "Soup noodles": ["chinese", "japanese"],
    "Braised lamb": ["chinese", "moroccan"],
    "Fried noodles": ["chinese", "thai", "japanese"],
    "Grilled salmon sushi": ["japanese"],
    "Lotus seed pork belly soup": ["chinese"],
    "Pickled fresh": ["chinese"],  # assumed Sichuan pickled fish dish -gpt
    "Pepper rabbit": ["chinese"],
    "Beef tendon noodles": ["chinese"],
    "Arctic bay sashimi": ["japanese"],
    "Braised sheep’s hoof": ["chinese"],
    "Cucumber dip": ["greek", "middle eastern"],  # tzatziki-like; default to greek -gpt
    "Chicken rice": ["singaporean", "malaysian"],
    "Sweet potato balls with taro": ["taiwanese", "chinese"],
    "Egg pancakes": ["chinese", "korean"],
    "Braised pork with chestnut": ["chinese"],
    "Stewed foie gras": ["french"],
    "Pickled fish rice noodles": ["chinese"],
    "Pork head meat mixed with cucumber": ["chinese"],
    "Black rice porridge": ["chinese", "korean"],
    "Griddle ribs": ["chinese"],
    "Sauce beef": ["chinese"],
    "Salt and pepper shrimp": ["chinese"],
    "Stewed chicken soup with cordyceps flower": ["chinese"],
    "Sour soup pork": ["chinese"],
    "Braised pigeon": ["chinese"],
    "Sausage pizza": ["italian", "american"],
    "Candied sweet potatoes": ["chinese", "american"],
    "Shrimp sushi": ["japanese"],
    "Fried noodles with seafood": ["chinese", "japanese"],
    "Griddle of pleurotus eryngii": ["chinese"],
    "Fried beans": ["chinese"],
    "The five-star chicken nuggets": ["chinese"],  # playful name, assumed Chinese -gpt
    "Broth bottom": ["chinese"],  # likely refers to hot pot soup base -gpt
    "Pilaf": ["uzbekistani", "russian"],
    "Griddle beef with skin": ["chinese"],
    "Cold dried eggs": ["chinese"],  # likely cold dish preparation -gpt
    "Celery and peanuts": ["chinese"],
    "Sauerkraut chicken": ["chinese"],
    "Pickled cucumber": ["russian", "german", "chinese"],
    "Potted cake": ["chinese"],
    "Rice burger": ["japanese", "korean"],
    "Mango fried yogurt": ["thai"],  # modern dessert fusion, likely Thai -gpt
    "Sawdust cup": ["portuguese"],  # traditional dessert -gpt
    "Fresh pot rabbit": ["chinese"],
    "Mango sticky rice cake": ["thai"],
    "Honey roasted whole chicken": ["american", "chinese"],
    "Shredded cake": ["chinese"],
    "Tenderloin skewers": ["turkish", "chinese"],
    "Salmon salad": ["japanese", "american"],
    "Dry roasted large yellow croaker": ["chinese"],
    "Fish skin dumplings": ["chinese"],
    "Signature chicken feet": ["chinese"],
    "Pimple face": ["chinese"],  # likely refers to “flour pimple” noodles -gpt
    "Fried lamb chops": ["chinese", "greek"],
    "Stir-fried squid whiskers": ["chinese"],
    "Fried five spice roll": ["chinese"],
    "Crock soup": ["chinese"],  # refers to slow-simmered soups -gpt
    "Tofu bubble": ["chinese"],
    "Dried radish omelette": ["chinese", "taiwanese"],
    "Shredded potato burrito": ["chinese"],  # fusion-style wrap -gpt
    "Scrambled eggs with green onion": ["chinese"],
    "Mixed beef": ["chinese"],  # variety beef cold dish -gpt
    "Garlic bread": ["italian", "american"],
    "Sauteed pork with green beans": ["chinese"],
    "Braised vermicelli with chicken and mushroom": ["chinese"],
    "Oreo ice cream": ["american"],
    "Braised ham sausage": ["chinese"],
    "Stir-fried pork with green peppers": ["chinese"],
    "Sauerkraut vermicelli soup": ["chinese"],
    "Organic fish": ["chinese"],  # broad term, assumed local Chinese prep -gpt
    "Shredded squid": ["japanese", "chinese"],
    "Spicy fried escargot": ["chinese", "french"],
    "Honey chicken feet": ["chinese"],
    "Cucumber mixed with garlic paste": ["chinese"],
    "Watermelon smoothie": ["american", "filipino"],  # Filipino has similar drinks -gpt
    "Scallops and shrimp congee": ["chinese"],
    "Multigrain bun": ["chinese"],
    "Cold preserved egg": ["chinese"],
    "Stir-fried lettuce with dace in black bean sauce": ["chinese"],
    "Pickled cabbage powder": ["chinese"],  # likely pickled cabbage with ground rice noodles -gpt
    "Stone egg skewers": ["chinese"],  # possibly quail eggs or tea eggs on skewers -gpt
    "Sauteed beef fillet with hot green pepper": ["chinese"],
    "Chicken breast salad": ["american", "french"],
    "Chocolate brown cake": ["american"],
    "Cucumber fritters": ["indian", "chinese"],  # tempura or pakora-style -gpt
    "Steamed pork ribs": ["chinese"],
    "Sea star": ["chinese"],  # eaten as seafood in some Chinese regions -gpt
    "Fried dried tofu": ["chinese"],
    "Fried sweet potato balls": ["taiwanese", "chinese"],
    "Guiling paste": ["chinese"],
    "Green vegetable tofu soup": ["chinese"],
    "Mapo tofu": ["chinese"],
    "Grilled fatty intestine skewers": ["chinese"],
    "Pan-fried pork bun": ["chinese"],
    "Braised turtle": ["chinese"],
    "Cilantro tofu soup": ["chinese"],
    "Fried rice with sauerkraut and egg": ["chinese"],
    "Mustard pork noodles": ["chinese"],
    "Polenta": ["italian"],
    "Pork noodles": ["chinese"],
    "Spicy squid": ["korean", "chinese", "japanese"],
    "Ketchup surface": ["chinese"],  # likely ketchup noodles or sauce topping -gpt
    "Grilled cod": ["japanese", "norwegian"],
    "Ice cream cone": ["american"],
    "Large rows of rice": ["chinese"],  # likely refers to rice with pork chops -gpt
    "Chestnut shortbread": ["chinese"],
    "Marinated goose wings": ["chinese"],
    "Vegetarian abalone": ["chinese"],
    "Ice cream ball": ["american"],
    "Fried ham with cucumber": ["chinese"],
    "Piggy paige cake": ["chinese"],  # novelty bakery item -gpt
    "Chicken sandwich": ["american"],
    "Mango black jelly": ["taiwanese", "chinese"],
    "Roast chicken": ["american", "chinese"],
    "Walnut buns": ["chinese"],
    "Braised tofu in abalone sauce": ["chinese"],
    "The oil meat": ["chinese"],  # likely refers to greasy pork dish -gpt
    "Cheese ribs": ["korean", "american"],
    "Fried dumplings": ["chinese", "japanese"],
    "Sushi of floss": ["japanese", "chinese"],  # pork floss sushi -gpt
    "Yongzhou blood duck": ["chinese"],
    "Braised beef brisket en casserole": ["chinese"],
    "Preserved rice": ["chinese"],  # possibly refers to claypot rice with preserved meats -gpt
    "Guokui": ["chinese"],
    "Fried rice cake with chinese cabbage": ["chinese"],
    "Stewed bean curd soup with crucian carp": ["chinese"],
    "Smoothies": ["american"],
    "Elbow": ["chinese"],  # likely refers to pork elbow/hock -gpt
    "Cheese baked scallops": ["japanese", "chinese"],
    "Sauerkraut bass": ["chinese"],
    "Bean buns": ["chinese"],
    "Durian pizza": ["malaysian", "thai"],  # modern SE Asian fusion -gpt
    "Boiled dried shreds": ["chinese"],  # likely noodle shreds or tofu skin -gpt
    "Steamed chicken feet with black bean sauce": ["chinese"],
    "Blueberry mousse": ["french", "american"],
    "Fried rice noodles with eggs": ["chinese", "thai"],
    "Rice with duck legs": ["chinese"],
    "Tofu with shallots": ["chinese"],
    "Tomahaw": ["american"],  # likely tomahawk steak -gpt
    "Bacon sandwich": ["american", "british"],
    "Braised eggplant with bean curd": ["chinese"],
    "Donkey burger": ["chinese"],
    "Braised fish with soy sauce": ["chinese"],
    "Rice covered with black pepper steak": ["chinese", "japanese"],
    "Italian noodle with meat sauce": ["italian"],
    "Rice with teriyaki drumstick": ["japanese"],
    "Duck blood and bean-starchy vermicelli soup": ["chinese"],
    "Sauteed lettuce": ["chinese"],
    "Ice powder": ["chinese"],  # Sichuan dessert -gpt
    "Egg wrapped sausage": ["korean", "chinese"],
    "Rainbow cake": ["american"],
    "Blueberry smoothie": ["american"],
    "Lava cake": ["french", "american"],
    "Stir fried vermicelli": ["chinese"],
    "Fried shrimp": ["japanese", "chinese", "american"],
    "Fried squid flower": ["chinese"],
    "Stewed croaker in brown sauce": ["chinese"],
    "Quick-fried liver with distilled grains sauce": ["chinese"],
    "Pita bread so awked in beef soup": ["chinese"],  # likely typo for “soaked” – Yangrou Paomo -gpt
    "Vinegar turnip": ["chinese"],
    "Wonton": ["chinese"],
    "Beef soup": ["chinese"],
    "Muxu pork": ["chinese"],
    "Seaweed sushi": ["japanese"],
    "Steamed turbot": ["chinese"],
    "Larimichthys": ["chinese"],  # fish species often prepared in China -gpt
    "Fried chicken": ["american", "korean", "chinese"],
    "Salted pork in jelly crystal trotter": ["chinese"],
    "Flower cake": ["chinese"],
    "Barbecued pork noodle rolls": ["chinese"],
    "Potato chips on sizzling iron plate": ["chinese"],
    "Fried bean sprouts with leek": ["chinese"],
    "Sesame octopus": ["japanese", "chinese"],
    "Fried razor clam": ["chinese"],
    "Cheese pizza": ["italian", "american"],
    "Pork with garlic sauce": ["chinese"],
    "Scalded beef": ["chinese"],
    "Sugar oil cake": ["chinese"],
}

print(len(food_to_cuisines))