food_to_cuisines = {
"Grilled beef tongue": ["argentine", "brazilian", "mexican", "south_african", "american", "chilean", "colombian", "peruvian", "uruguayan", "bolivian", "venezuelan", "cuban", "dominican", "paraguayan"],
"Flavored snail meat": ["french", "belgian", "italian", "spanish", "portuguese", "algerian", "moroccan", "tunisian", "lebanese", "egyptian", "turkish", "greek"],
"Napoleon cake": ["french", "russian", "belarusian", "ukrainian", "polish", "latvian", "lithuanian", "estonian", "moldovan", "romanian", "bulgarian", "serbian", "croatian", "hungarian", "czech", "slovak", "slovene"],
"Spicy chicken": ["thai", "indian", "pakistani", "bangladeshi", "malaysian", "indonesian", "mexican", "american", "korean", "chinese", "vietnamese", "lebanese", "turkish", "ethiopian", "moroccan", "south_african", "ghanaian", "nigerian"],
"Noodles with pork chop": ["chinese", "filipino", "malaysian", "taiwanese", "thai", "vietnamese", "japanese", "korean"],
"Stir-fried pork with capers": ["italian", "spanish", "french", "greek"],
"Bang bang chicken": ["chinese", "taiwanese", "malaysian", "singaporean"],
"Hibiscus crab stick": ["jamaican", "bahamian", "american_islander"],
"Tomato and egg flour pimple soup": ["chinese"],
"Grilled ribs": ["american", "argentine", "brazilian", "south_african", "korean", "mexican"],
"Stir-fried lettuce": ["chinese", "thai", "vietnamese", "filipino", "malaysian"],
"Stir-fried clams with chili sauce": ["chinese", "thai", "vietnamese", "filipino"],
"Brownie": ["american", "canadian", "british", "australian", "new_zealander"],
"Duck feet": ["chinese", "thai", "vietnamese", "malaysian"],
"Hand cake": ["chinese", "taiwanese"],
"Durian pancake": ["malaysian", "indonesian", "thai", "singaporean"],
"Griddle rabbit": ["french", "italian", "spanish", "greek"],
"Dried chiba bean curd": ["chinese", "taiwanese"],
"Plate reinforcement": [], # Uncertain, no cuisine assigned -gpt
"Tobiko warship sushi": ["japanese"],
"Meringue puffs": ["french", "austrian", "swiss", "belgian", "italian"],
"Fried pork with sauerkraut": ["german", "polish", "czech", "austrian", "hungarian"],
"Potato salad": ["german", "austrian", "american", "polish", "russian", "ukrainian", "finnish", "swedish", "norwegian", "danish"],
"Onion mixed fungus": ["chinese"],
"Crepe": ["french", "belgian", "swiss"],
"Crispy chicken bibimbap": ["korean"],
"Golden cake": ["american", "british", "australian", "new_zealander"],
"Bean sprouts in soup": ["chinese", "vietnamese", "thai", "filipino"],
"Steamed fish head with double pepper": ["chinese"],
"Mung bean soup": ["chinese", "indian", "thai", "vietnamese", "filipino", "malaysian"],
"Good harvest of coarse grains": [], # Uncertain, no cuisine assigned -gpt
"Crab fried rice cake": ["chinese", "korean", "thai", "vietnamese"],
"Chicken casserole": ["french", "american", "british", "australian", "canadian"],
"Pan-fried three stuffed treasures": ["chinese"],
"Firewood chicken": ["chinese", "taiwanese"],
"Golden cod": ["american", "british", "french", "finnish", "icelander", "norwegian"],
"Waxiang chicken": ["chinese"],
"Corn with pine nuts": ["armenian", "georgian", "turkish", "iranian"],
"Secret jujube": ["chinese", "korean"],
"Pork with preserved vegetable": ["chinese"],
"Fried hairtail": ["chinese", "korean", "japanese"],
"Yogurt purple rice": ["thai", "indian", "pakistani", "bangladeshi", "nepalese"],
"Home-style bean curd": ["chinese"],
"Double chicken drumsticks": ["american", "chinese", "korean"],
"Fried crab with curry": ["indian", "thai", "malaysian", "singaporean"],
"Fried cantonese sausage": ["chinese"],
"Roasted eggplant with garlic": ["greek", "turkish", "armenian", "lebanese", "egyptian"],
"Shrimp skewers": ["american", "japanese", "korean", "thai", "malaysian"],
"Wonton noodles": ["chinese", "malaysian", "singaporean"],
"Fried kidney flower with pig liver": ["chinese"],
"Vinegar cabbage": ["chinese", "korean"],
"Crab roe salad": ["chinese", "japanese", "korean"],
"Fried eggplant": ["greek", "italian", "spanish", "turkish", "chinese"],
"Four red porridge": ["chinese", "thai"],
"Boiled fish": ["chinese", "thai", "vietnamese"],
"Grilled chicken feet": ["chinese", "thai", "vietnamese"],
"Roast eggplants": ["greek", "turkish", "armenian", "lebanese", "egyptian"],
"Kidney beans": ["mexican", "american", "indian", "brazilian", "south_african", "jamaican"],
"Straw hat cake": ["chinese", "taiwanese"],
"Meicai bamboo shoots": ["chinese"],
"Cold pork cold head": ["german", "polish", "austrian", "czech"],
"Braised duck gizzards": ["chinese"],
"Wasabi octopus": ["japanese"],
"Cheese baked sweet potatoes": ["american", "canadian", "british"],
"Fried twist": ["chinese"],
"Dumplings": ["chinese", "japanese", "korean", "polish", "russian", "ukrainian", "mongolian", "romanian", "bulgarian", "croatian", "serbian"],
"Tomato pasta": ["italian"],
"Dried carob": ["turkish", "greek", "lebanese"],
"Toffee cake": ["american", "british", "australian"],
"Crab yellow tofu": ["chinese"],
"Barbecue ribs": ["american", "korean", "chinese", "brazilian", "argentine", "mexican"],
"Strawberry sundae": ["american", "canadian", "british", "australian"],
"Pineapple rice": ["thai", "indian", "indonesian", "malaysian", "filipino"],
"Tin foil potatoes": ["american", "british", "canadian", "australian"],
"Stir-fried pork with rice white": ["chinese"],
"Black pepper pork chop rice": ["chinese", "malaysian", "singaporean"],
"Ribs rice": ["american", "chinese", "korean"],
"Braised noodles with ribs": ["chinese", "taiwanese"],
"Spicy shrimp": ["thai", "mexican", "indian", "filipino", "chinese", "malaysian"],
"Choy sum with garlic sauce": ["chinese"],
"Steamed chicken in lotus leaves": ["chinese", "malaysian", "singaporean"],
"Spicy cabbage fried rice": ["korean", "chinese", "thai"],
"Pineapple fritters shrimp": ["filipino", "thai", "malaysian"],
"Spicy shao pointed": ["chinese"],
"Scallion lamb": ["chinese", "mongolian", "kazakhstani", "turkish"],
"Bazhen tofu": ["chinese"],
"Donkey meat": ["chinese", "mongolian", "italian"],
"Fried egg roll": ["chinese", "filipino", "vietnamese"],
"Gourd head bread in the soup": ["chinese"],
"Fish head tofu soup": ["chinese"],
"Fried spring rolls with three pieces of silk": ["chinese", "vietnamese", "filipino"],
"Braised beef brisket on rice": ["chinese", "taiwanese"],
"Smoked fish": ["finnish", "russian", "american", "canadian", "german", "british", "icelander", "norwegian"],
"Fried rice noodles with eggs": ["chinese", "thai", "malaysian", "filipino"],
"Corn ribs soup": ["chinese"],
"Rib skewers": ["chinese", "korean", "american"],
"Fried shao mai": ["chinese"],
"Shredded potatoes with salad": ["russian", "ukrainian", "polish", "german"],
"Glutinous rice balls with peanuts and sesame seed": ["chinese", "taiwanese"],
"Fried potato chips with spicy cabbage": ["american", "korean", "chinese"],
"Crab stick nigiri sushi": ["japanese"],
"Steamed pumpkin with red dates": ["chinese", "taiwanese", "korean", "japanese"],
"Coconut jelly": ["filipino", "thai", "vietnamese", "indonesian", "malaysian", "brazilian", "american_islander", "american_samoan"],
"Fried edamame with pickled vegetables": ["japanese", "korean", "chinese"],
"Braised pork on rice": ["chinese", "taiwanese", "malaysian", "singaporean", "filipino", "vietnamese", "thai"],
"Braised chicken nuggets": ["american", "american_islander", "american_samoan", "british", "australian"],
"Preserved egg with hot pepper": ["chinese", "taiwanese", "malaysian", "singaporean", "thai"],
"Green tea cake": ["japanese", "taiwanese", "chinese", "korean"],
"White rice": ["afghan", "albanian", "algerian", "american", "american_islander", "american_samoan", "armenian", "australian", "azerbaijani", "bangladeshi", "belgian", "brazilian", "british", "burmese", "cambodian", "canadian", "chilean", "colombian", "croatian", "cuban", "cypriot", "czech", "danish", "dutch", "ecuadorean", "egyptian", "emirati", "ethiopian", "filipino", "finnish", "french", "georgian", "german", "ghanaian", "greek", "guatemalan", "haitian", "hungarian", "indian", "indonesian", "iranian", "iraqi", "israeli", "italian", "jamaican", "japanese", "jordanian", "kenyan", "kuwaiti", "laotian", "lebanese", "malaysian", "mexican", "moroccan", "nepalese", "norwegian", "pakistani", "panamanian", "peruvian", "polish", "portuguese", "qatari", "romanian", "russian", "saudi_arabian", "senegalese", "serbian", "singaporean", "slovak", "slovene", "south_african", "south_korean", "spanish", "sri_lankan", "swedish", "swiss", "syrian", "taiwanese", "thai", "tunisian", "turkish", "ukrainian", "uruguayan", "uzbekistani", "vietnamese", "yemeni", "zambian", "zimbabwean"],  # staple across almost all listed cuisines -gpt
"Pork liver noodle": ["chinese", "taiwanese", "malaysian", "singaporean", "thai", "vietnamese"],
"Spicy fish": ["thai", "vietnamese", "chinese", "indonesian", "malaysian", "mexican", "nigerian"],
"Sauerkraut beef": ["german", "austrian", "polish", "czech", "hungarian", "slovak", "slovene", "ukrainian", "russian"],
"Lotus pond side dishes": ["chinese", "taiwanese", "japanese", "korean", "thai", "vietnamese"],
"Green pepper stir-fried dregs": ["chinese", "taiwanese"],
"Fried bacon with bamboo shoots": ["chinese", "taiwanese", "thai"],
"Grilled prawns": ["spanish", "portuguese", "italian", "filipino", "thai", "vietnamese", "indonesian", "malaysian", "mexican", "american", "australian"],
"Grilled duck intestine skewers": ["chinese", "taiwanese", "thai", "indonesian"],
"Stir-fried beef fillet with tea mushroom": ["chinese", "taiwanese", "malaysian", "singaporean"],
"Scrambled noodles with tomato and egg": ["chinese", "taiwanese", "filipino", "thai"],
"Snowflake chicken fillet": ["chinese", "taiwanese"],
"Refreshing evergreen": [],  # uncertain dish name; no cuisine assigned -gpt
"Fried chicken gizzards": ["american", "american_islander", "american_samoan", "filipino", "thai", "chinese", "mexican", "ghanaian", "nigerian"],
"Scallion sea bass": ["chinese", "taiwanese", "japanese", "korean", "vietnamese", "thai"],
"Red date and yam congee": ["chinese", "taiwanese", "korean", "japanese"],
"Coarse grain porridge": ["chinese", "korean", "japanese", "afghan", "bangladeshi", "indian", "pakistani", "ethiopian"],
"Stewed chicken nuggets": ["american", "american_islander", "american_samoan", "chinese"],
"Spicy pork": ["chinese", "thai", "mexican", "korean", "filipino", "vietnamese"],
"Pickled mustard": ["chinese", "taiwanese", "korean", "japanese"],
"Matcha mousse cake": ["japanese"],
"Snowflake cowboy bones": ["american"],
"Fried flower beetle": [],  # uncommon dish; no cuisine assigned -gpt
"Roast pork": ["chinese", "british", "american", "filipino", "italian", "german", "french"],
"Flamingo cake": [],  # unknown dish; no cuisine assigned -gpt
"Colorful face lift": [],  # unclear dish name; no cuisine assigned -gpt
"Cool coconut milk": ["filipino", "thai", "vietnamese", "malaysian", "indonesian", "american_islander", "american_samoan"],
"Tossed fish skin": ["chinese", "taiwanese", "malaysian", "singaporean"],
"Sparerib noodles": ["chinese", "taiwanese", "malaysian", "singaporean", "thai"],
"Boneless chicken feet": ["chinese", "taiwanese"],
"Pork sauerkraut bun": ["chinese", "taiwanese"],
"Soy milk": ["chinese", "taiwanese", "japanese", "korean", "indonesian", "malaysian"],
"Beef brisket noodle": ["chinese", "taiwanese", "malaysian", "singaporean"],
"Five recipes of tender beef": [],  # vague dish name; no cuisine assigned -gpt
"Fried pork with pleurotus eryngii": ["chinese", "taiwanese"],
"Griddle chicken": ["american", "british", "australian", "filipino", "mexican"],
"Red bean curd": ["chinese", "taiwanese", "japanese"],
"Custard bun": ["chinese", "taiwanese", "filipino"],
"Fried lotus white with oil residue": ["chinese", "taiwanese"],
"Kimchi beef sushi": ["japanese", "korean"],
"Red bean double skin milk": ["chinese", "taiwanese"],
"Mutton soup": ["afghan", "algerian", "armenian", "azerbaijani", "bangladeshi", "british", "chinese", "egyptian", "ethiopian", "indian", "iranian", "iraqi", "kazakhstani", "korean", "lebanese", "mongolian", "moroccan", "pakistani", "russian", "saudi_arabian", "somali", "sudanese", "syrian", "tadzhik", "turkish", "uzbekistani", "yemeni"],
"Fire bun": ["chinese", "taiwanese"],
"Beef and rice noodle soup": ["chinese", "taiwanese", "vietnamese", "thai"],
"Fried mushrooms": ["american", "british", "chinese", "french", "italian"],
"Stir-fried shredded pork with garlic moss": ["chinese", "taiwanese"],
"Smooth double skin milk": ["chinese", "taiwanese"],
"Soy bean curd": ["chinese", "taiwanese", "japanese", "korean"],
"Beef claypot rice": ["chinese", "taiwanese", "malaysian", "singaporean"],
"Fried chicken chop": ["american", "british", "australian", "filipino"],
"Refreshing lotus root slices": ["chinese", "taiwanese", "japanese", "korean"],
"Fried shredded pancake": ["chinese", "taiwanese"],
"Hot pot noodles": ["chinese", "taiwanese", "japanese", "korean", "thai"],
"Fried pork with chili": ["chinese", "thai", "filipino", "mexican"],
"Saute spicy chicken": ["american", "thai", "mexican", "indian"],
"Pork with preserved vegetable rice": ["chinese", "taiwanese"],
"Tiramisu cake": ["italian", "american", "french"],
"Soy sauce fish": ["chinese", "taiwanese", "japanese", "korean"],
"Baked potato chips": ["american", "british", "australian", "canadian"],
"Cream of mushroom soup": ["american", "british", "french", "canadian", "australian"],
"Baked fairy grass with Taro": [],  # unclear dish; no cuisine assigned -gpt
"Baked corn with egg yolk": ["chinese", "taiwanese", "thai"],
"Steam pot chicken": ["chinese", "taiwanese"],
"Tomato and egg soup": ["chinese", "taiwanese", "filipino", "thai", "vietnamese"],
"River noodles in pig soup": ["chinese", "taiwanese"],
"Matcha yellow peach cake": ["japanese", "taiwanese"],
"Fruit pizza": ["american", "canadian", "british", "australian"],
"Sweet plum and sweet potato": ["chinese", "taiwanese", "japanese", "korean"],
"Cucumber preserved egg soup": ["chinese", "taiwanese"],
"Scrambled egg with chopped chili pepper": ["chinese", "taiwanese", "thai", "filipino"],
"Pineapple cake": ["taiwanese", "filipino", "american", "malaysian"],
"Fried balls and radish": ["chinese", "taiwanese", "japanese"],
"Steamed abalone with garlic and vermicelli": ["chinese", "taiwanese", "japanese"],
"Overlord chicken strips": [],  # unclear dish; no cuisine assigned -gpt
"Braised chicken": ["chinese", "taiwanese", "american", "filipino", "french", "italian"],
"Three delicacies in casserole": ["chinese", "taiwanese"],
"Crispy corn cob": ["american", "mexican", "filipino"],
"Steamed mandarin fish": ["chinese", "taiwanese"],
"Chinese salad": ["chinese", "taiwanese"],
"Hotbed chives with pork": ["chinese", "taiwanese"],
"Clam tofu soup": ["chinese", "taiwanese", "japanese", "korean"],
"Tuna onigiri": ["japanese"],
"Beef ribs": ["american", "korean", "mexican", "filipino", "chinese"],
"Spicy cabbage sushi roll": ["japanese", "korean"],
"Pickled mustard with shredded soup": ["chinese", "taiwanese"],
"Red oil dumplings": ["chinese", "taiwanese"],
"Fried shrimp": ["american", "chinese", "thai", "filipino", "mexican"],
"Crispy radish skin": ["chinese", "taiwanese"],
"Fried tofu": ["chinese", "taiwanese", "japanese", "korean", "indonesian", "malaysian"],
"Salted chicken": ["chinese", "taiwanese", "thai", "malaysian", "filipino"],
"Baked pig brain with tin foil": ["chinese", "taiwanese"],
"Sour and spicy fish meal with grain": ["chinese", "thai", "vietnamese", "indonesian", "malaysian"],
"Hotbed chives with pork": ["chinese"],
"Clam tofu soup": ["chinese", "japanese", "korean"],
"Tuna onigiri": ["japanese"],
"Beef ribs": ["american", "argentine", "australian", "brazilian", "canadian", "chilean", "chinese", "colombian", "cuban", "french", "german", "italian", "japanese", "korean", "mexican", "new_zealander", "peruvian", "philippine", "polish", "portuguese", "russian", "south_african", "south_korean", "spanish", "thai", "turkish", "vietnamese"],
"Spicy cabbage sushi roll": ["japanese", "korean"],
"Pickled mustard with shredded soup": ["chinese", "vietnamese", "thai"],
"Red oil dumplings": ["chinese"],
"Fried shrimp": ["american", "argentine", "australian", "brazilian", "canadian", "chinese", "french", "indian", "indonesian", "italian", "japanese", "korean", "malaysian", "mexican", "philippine", "portuguese", "russian", "singaporean", "spanish", "thai", "vietnamese"],
"Crispy radish skin": ["chinese"],
"Fried tofu": ["chinese", "japanese", "indonesian", "korean", "malaysian", "singaporean", "thai", "vietnamese"],
"Salted chicken": ["chinese", "taiwanese", "malaysian", "singaporean"],
"Baked pig brain with tin foil": ["chinese"],  # -gpt
"Sour and spicy fish meal with grainpicy korean noodles": ["chinese", "korean"],  # Assuming typo in dish name -gpt
"Steamed rice with mei cai meatloaf": ["chinese"],
"King crab": ["american", "canadian", "chinese", "japanese", "korean", "norwegian", "russian", "thai"],
"Beef noodle soup": ["chinese", "taiwanese", "vietnamese"],
"Fried frog": ["chinese", "french", "thai", "vietnamese"],
"Mustard duck feet": ["chinese"],
"Fried squid": ["chinese", "filipino", "indonesian", "italian", "japanese", "korean", "portuguese", "spanish", "thai"],
"Cucumber with pork ears": ["chinese"],
"Oily noodles": ["chinese"],
"Red oil yuba": ["chinese"],
"Soup noodles": ["chinese", "japanese", "korean", "taiwanese", "vietnamese"],
"Braised lamb": ["afghan", "algerian", "armenian", "chinese", "egyptian", "greek", "iranian", "iraqi", "israeli", "jordanian", "kazakhstani", "lebanese", "libyan", "moroccan", "pakistani", "saudi_arabian", "sudanese", "syrian", "tajik", "turkish", "uzbekistani", "yemeni"],
"Fried noodles": ["chinese", "filipino", "indonesian", "japanese", "korean", "malaysian", "singaporean", "thai", "vietnamese"],
"Grilled salmon sushi": ["japanese"],
"Lotus seed pork belly soup": ["chinese"],
"Pickled fresh": ["chinese"],  # Ambiguous; assumed to be pickled vegetables -gpt
"Pepper rabbit": ["chinese", "italian", "spanish", "french"],
"Beef tendon noodles": ["chinese", "vietnamese"],
"Arctic bay sashimi": ["japanese", "norwegian", "russian"],
"Braised sheep’s hoof": ["chinese", "iranian", "moroccan"],
"Cucumber dip": ["greek", "turkish", "iranian", "lebanese", "armenian"],
"Chicken rice": ["malaysian", "singaporean", "thai", "chinese"],
"Sweet potato balls with taro": ["taiwanese", "chinese", "filipino", "vietnamese"],
"Egg pancakes": ["chinese", "korean", "taiwanese"],
"Braised pork with chestnut": ["chinese"],
"Stewed foie gras": ["french"],
"Pickled fish rice noodles": ["chinese", "thai", "vietnamese"],
"Pork head meat mixed with cucumber": ["chinese"],
"Black rice porridge": ["chinese", "korean", "thai", "vietnamese"],
"Griddle ribs": ["chinese"],
"Sauce beef": ["chinese"],  # Assumed cold spiced beef slices -gpt
"Salt and pepper shrimp": ["chinese", "filipino"],
"Stewed chicken soup with cordyceps flower": ["chinese"],
"Sour soup pork": ["chinese", "vietnamese", "thai"],
"Braised pigeon": ["chinese", "french"],
"Sausage pizza": ["italian", "american"],
"Candied sweet potatoes": ["chinese", "american", "japanese", "korean"],
"Shrimp sushi": ["japanese"],
"Fried noodles with seafood": ["chinese", "filipino", "indonesian", "japanese", "korean", "malaysian", "singaporean", "thai", "vietnamese"],
"Griddle of pleurotus eryngii": ["chinese"],
"Fried beans": ["chinese", "indian", "ethiopian", "mexican"],
"The five-star chicken nuggets": ["american"],
"Broth bottom": ["chinese"],  # Generic soup base -gpt
"Pilaf": ["afghan", "armenian", "azerbaijani", "bangladeshi", "georgian", "indian", "iranian", "iraqi", "kazakhstani", "lebanese", "pakistani", "russian", "syrian", "tajik", "turkish", "turkmen", "uzbekistani"],
"Griddle beef with skin": ["chinese"],
"Cold dried eggs": ["chinese"],  # Assumed a preserved egg dish -gpt
"Celery and peanuts": ["chinese"],
"Sauerkraut chicken": ["chinese", "german", "russian", "ukrainian"],
"Pickled cucumber": ["chinese", "german", "polish", "russian", "ukrainian", "jewish"],
"Potted cake": ["chinese"],  # Assumed Cantonese-style steamed dessert -gpt
"Rice burger": ["japanese", "korean", "taiwanese"],
"Mango fried yogurt": ["thai", "indian", "filipino"],  # Fusion-style; yogurt frying uncommon -gpt
"Sawdust cup": ["portuguese"],
"Fresh pot rabbit": ["chinese", "italian", "french", "spanish"],
"Mango sticky rice cake": ["thai"],
"Honey roasted whole chicken": ["american", "chinese", "filipino", "french"],
"Shredded cake": ["chinese"],  # Assumed Shaobing or similar -gpt
"Tenderloin skewers": ["chinese", "turkish", "iranian", "pakistani", "afghan", "argentine", "brazilian"],
"Salmon salad": ["american", "canadian", "japanese", "norwegian", "russian"],
"Dry roasted large yellow croaker": ["chinese"],
"Fish skin dumplings": ["chinese"],
"Signature chicken feet": ["chinese", "filipino"],
"Pimple face": ["chinese"],  # Unclear; possibly a humorous or local name for a spicy dish -gpt
"Fried lamb chops": ["chinese", "greek", "iranian", "turkish", "french"],
"Stir-fried squid whiskers": ["chinese", "japanese", "korean"],
"Fried five spice roll": ["chinese", "taiwanese", "vietnamese"],
"Crock soup": ["chinese"],
"Tofu bubble": ["chinese", "taiwanese"],
"Dried radish omelette": ["chinese", "japanese", "taiwanese"],
"Shredded potato burrito": ["chinese"],  # Likely fusion dish -gpt
"Scrambled eggs with green onion": ["chinese", "japanese", "korean"],
"Mixed beef": ["chinese"],
"Garlic bread": ["italian", "french", "american"],
"Sauteed pork with green beans": ["chinese"],
"Braised vermicelli with chicken and mushroom": ["chinese"],
"Oreo ice cream": ["american"],
"Braised ham sausage": ["chinese", "german", "polish"],
"Stir-fried pork with green peppers": ["chinese"],
"Sauerkraut vermicelli soup": ["chinese"],
"Organic fish": ["chinese", "japanese", "french", "american"],
"Shredded squid": ["chinese", "japanese", "korean"],
"Spicy fried escargot": ["chinese", "french", "vietnamese"],
"Honey chicken feet": ["chinese"],
"Cucumber mixed with garlic paste": ["chinese", "lebanese", "iranian"],
"Watermelon smoothie": ["american", "filipino", "thai"],
"Scallops and shrimp congee": ["chinese"],
"Multigrain bun": ["chinese", "korean", "japanese"],
"Cold preserved egg": ["chinese"],
"Stir-fried lettuce with dace in black bean sauce": ["chinese"],
"Pickled cabbage powder": ["chinese"],
"Stone egg skewers": ["chinese"],
"Sauteed beef fillet with hot green pepper": ["chinese"],
"Chicken breast salad": ["american", "french", "canadian", "australian", "british", "new_zealander"],
"Chocolate brown cake": ["american", "british", "australian", "canadian", "french", "german"],
"Cucumber fritters": ["indian", "pakistani", "bangladeshi", "nepalese", "american"],
"Steamed pork ribs": ["chinese"],
"Sea star": ["chinese", "japanese", "korean", "filipino"],
"Fried dried tofu": ["chinese", "japanese", "korean", "vietnamese"],
"Fried sweet potato balls": ["filipino", "taiwanese", "thai"],
"Guiling paste": ["chinese"],
"Green vegetable tofu soup": ["chinese", "japanese", "korean", "vietnamese"],
"Mapo tofu": ["chinese"],
"Grilled fatty intestine skewers": ["chinese", "korean"],
"Pan-fried pork bun": ["chinese"],
"Braised turtle": ["chinese", "vietnamese", "thai"],
"Cilantro tofu soup": ["chinese", "vietnamese"],
"Fried rice with sauerkraut and egg": ["chinese"],
"Mustard pork noodles": ["chinese"],
"Polenta": ["italian"],
"Pork noodles": ["chinese", "vietnamese", "thai", "filipino", "japanese"],
"Spicy squid": ["korean", "japanese", "chinese", "filipino", "thai"],
"Ketchup surface": ["american"],  # Uncertain what this refers to -gpt
"Grilled cod": ["norwegian", "icelander", "danish", "swedish", "finnish", "british", "canadian"],
"Ice cream cone": ["american", "italian", "french", "british"],
"Large rows of rice": ["chinese"],  # Likely refers to a rice dish presentation -gpt
"Chestnut shortbread": ["chinese", "british"],
"Marinated goose wings": ["chinese"],
"Vegetarian abalone": ["chinese", "japanese", "korean"],
"Ice cream ball": ["american", "italian", "french"],
"Fried ham with cucumber": ["chinese", "american"],
"Piggy paige cake": ["chinese"],  # Likely a transliteration of a Chinese cake -gpt
"Chicken sandwich": ["american", "british", "australian", "canadian"],
"Mango black jelly": ["chinese", "thai", "filipino", "vietnamese"],
"Roast chicken": ["french", "american", "british", "italian", "spanish", "greek", "turkish", "moroccan", "lebanese", "south_african", "australian", "new_zealander"],
"Walnut buns": ["chinese"],
"Braised tofu in abalone sauce": ["chinese"],
"The oil meat": ["chinese"],  # Possibly a regional term for fatty pork -gpt
"Cheese ribs": ["american", "italian", "mexican", "australian"],
"Fried dumplings": ["chinese", "japanese", "korean"],
"Sushi of floss": ["japanese", "taiwanese", "malaysian", "singaporean"],
"Yongzhou blood duck": ["chinese"],
"Braised beef brisket en casserole": ["chinese", "french"],
"Preserved rice": ["chinese"],
"Guokui": ["chinese"],
"Fried rice cake with chinese cabbage": ["chinese"],
"Stewed bean curd soup with crucian carp": ["chinese"],
"Smoothies": ["american", "australian", "canadian", "british", "new_zealander"],
"Elbow": ["german", "czech", "polish", "hungarian"],  # Likely refers to pork elbow -gpt
"Cheese baked scallops": ["french", "japanese", "american"],
"Sauerkraut bass": ["german", "chinese"],
"Bean buns": ["chinese", "korean", "japanese"],
"Durian pizza": ["singaporean", "malaysian", "thai"],  # Fusion-style -gpt
"Boiled dried shreds": ["chinese"],  # Likely refers to a rehydrated vegetable dish -gpt
"Steamed chicken feet with black bean sauce": ["chinese"],
"Blueberry mousse": ["french", "american"],
"Fried rice noodles with eggs": ["chinese", "thai", "vietnamese", "malaysian"],
"Rice with duck legs": ["chinese", "french"],
"Tofu with shallots": ["chinese", "japanese", "korean"],
"Tomahaw": ["american"],  # Refers to tomahawk steak -gpt
"Bacon sandwich": ["british", "american"],
"Braised eggplant with bean curd": ["chinese"],
"Donkey burger": ["chinese"],
"Braised fish with soy sauce": ["chinese", "japanese", "filipino"],
"Rice covered with black pepper steak": ["chinese", "singaporean"],
"Italian noodle with meat sauce": ["italian"],
"Rice with teriyaki drumstick": ["japanese", "chinese"],
"Duck blood and bean-starchy vermicelli soup": ["chinese"],
"Sauteed lettuce": ["chinese"],
"Ice powder": ["chinese"],
"Egg wrapped sausage": ["japanese", "taiwanese"],
"Rainbow cake": ["american", "indonesian", "filipino"],
"Blueberry smoothie": ["american", "australian", "canadian", "new_zealander"],
"Lava cake": ["french", "american"],
"Stir fried vermicelli": ["chinese", "thai", "vietnamese", "malaysian", "filipino"],
"Fried shrimp": ["chinese", "thai", "filipino", "american", "japanese"],
"Fried squid flower": ["chinese", "japanese", "korean"],
"Stewed croaker in brown sauce": ["chinese"],
"Quick-fried liver with distilled grains sauce": ["chinese"],
"Pita bread so awked in beef soup": ["chinese"],  # Likely refers to Chinese-style bread soaked in soup -gpt
"Vinegar turnip": ["chinese"],
"Wonton": ["chinese"],
"Beef soup": ["chinese", "vietnamese", "korean", "thai", "mexican", "turkish", "iranian", "iraqi"],
"Muxu pork": ["chinese", "american"],
"Seaweed sushi": ["japanese"],
"Steamed turbot": ["chinese", "french", "british", "danish"],
"Larimichthys": ["chinese"],  # A genus of fish used in Chinese cuisine -gpt
"Fried chicken": ["american", "korean", "chinese", "japanese", "filipino", "south_african"],
"Salted pork in jelly crystal trotter": ["chinese"],
"Flower cake": ["chinese", "japanese"],
"Barbecued pork noodle rolls": ["chinese"],
"Potato chips on sizzling iron plate": ["chinese", "american"],
"Fried bean sprouts with leek": ["chinese", "korean"],
"Sesame octopus": ["japanese", "korean"],
"Fried razor clam": ["chinese", "japanese"],
"Cheese pizza": ["italian", "american"],
"Pork with garlic sauce": ["chinese"],
"Scalded beef": ["chinese"],
"Sugar oil cake": ["chinese"],
"Braised pork with vermicelli": ["chinese", "taiwanese", "malaysian", "singaporean", "filipino", "vietnamese"],
"Marinated quail eggs": ["chinese", "japanese", "filipino", "korean", "vietnamese", "thai"],
"Chinese chestnut": ["chinese"],
"Spicy beef soup": ["chinese", "korean", "thai", "vietnamese"],
"Boiled egg": ["american", "british", "canadian", "filipino", "french", "german", "indian", "japanese", "korean", "nigerian", "thai", "vietnamese"],  # Commonly featured as a side or topping -gpt
"Noodles soup": ["chinese", "japanese", "korean", "vietnamese", "thai", "malaysian", "indonesian", "filipino"],
"Braised pork": ["chinese", "taiwanese", "filipino", "vietnamese", "japanese", "korean"],
"Rice with curry chicken chop": ["malaysian", "singaporean", "chinese", "indian", "filipino"],
"Balsam pear scrambled eggs": ["chinese", "filipino", "vietnamese", "thai"],
"Roast chicken wings": ["american", "british", "australian", "canadian", "jamaican", "filipino", "brazilian"],
"Pork rice": ["chinese", "taiwanese", "filipino", "vietnamese"],
"Fried bacon with lettuce": ["american", "british", "canadian", "australian"],
"Fried eggs with pepper": ["american", "british", "filipino", "french", "german", "indian", "thai", "vietnamese"],
"Pork stomach": ["chinese", "filipino", "korean", "vietnamese", "thai"],
"Australian skewers": ["australian"],
"Steamed rice with barbecued pork": ["chinese", "filipino", "thai", "vietnamese"],
"Bread soaked in fish head soup": ["singaporean", "malaysian", "chinese"],
"Shredded pork skin": ["chinese", "filipino", "vietnamese"],
"Soy sauce chicken": ["chinese", "malaysian", "singaporean"],
"Tea flavored shrimp": ["chinese", "taiwanese"],
"Pita bread so awked in lamp soup": ["jordanian", "lebanese", "palestinian", "syrian", "iraqi", "saudi_arabian", "emirati", "kuwaiti", "qatar", "bahraini", "omani", "yemeni"],  # Assumed typo: soaked in lamb soup -gpt
"Scramble egg": ["american", "british", "canadian", "australian", "filipino", "french", "german", "japanese", "thai", "vietnamese"],
"Stewed chicken with mushroom": ["chinese", "filipino", "french", "italian", "vietnamese"],
"Grilled chicken breast": ["american", "british", "australian", "canadian", "filipino", "brazilian"],
"Oyster sauce beef": ["chinese", "thai", "filipino", "malaysian"],
"Stewed spareribs with potatoes": ["chinese", "filipino", "russian", "german", "ukrainian", "hungarian"],
"Marinated beef tripe": ["chinese", "mexican", "filipino", "vietnamese", "korean"],
"Sesame paste": ["chinese", "japanese", "korean", "lebanese", "syrian", "iranian", "israeli"],
"Coconut rice": ["filipino", "indonesian", "malaysian", "thai", "ghanaian", "nigerian"],
"Mother’s hoof soup": ["chinese", "filipino", "mongolian", "korean"],  # Assumed pork trotters -gpt
"Roasted fresh catfish": ["american", "nigerian", "thai", "vietnamese", "cambodian"],
"Fried pork with dried meat": ["chinese", "filipino", "vietnamese"],
"Coconut chicken": ["chinese", "filipino", "thai", "malaysian"],
"Steamed luffa with minced garlic": ["chinese", "vietnamese", "thai"],
"Spareribs with taro": ["chinese", "filipino"],
"Fried soybeans with luffa": ["chinese", "japanese", "korean"],
"Cod fish steak": ["british", "portuguese", "norwegian", "icelander", "american", "canadian"],
"Rice bag": ["chinese", "japanese", "korean", "vietnamese"],  # Assumed wrapped rice or zongzi-like item -gpt
"Pickle soup": ["polish", "ukrainian", "russian", "german", "czech", "hungarian"],
"Braised pork with braised pork": ["chinese", "taiwanese", "filipino"],  # Redundant name; assumed strong pork dish -gpt
"Fried shrimp": ["american", "chinese", "filipino", "thai", "japanese", "korean"],
"Salt and pepper duck chin": ["chinese"],
"Tofu pot": ["chinese", "japanese", "korean", "thai", "vietnamese"],
"Fried noodles with beef": ["chinese", "thai", "filipino", "indonesian", "malaysian"],
"Baked prawns with salt": ["chinese", "filipino", "thai", "malaysian"],
"Spicy hot pot": ["chinese", "korean", "thai"],
"Pork chop soup with radish": ["chinese", "taiwanese", "filipino", "korean"],
"Powder soup": ["chinese", "vietnamese", "thai"],  # Assumed starch or rice-based soup -gpt
"Spicy fish": ["chinese", "thai", "korean", "nigerian", "indian"],
"Whitebait soup": ["chinese", "japanese", "filipino", "italian"],
"Mixed agaric with coriander": ["chinese", "vietnamese", "thai"],
"Bamboo rice": ["chinese", "thai", "vietnamese", "indonesian", "malaysian"],
"Braised eggplant with meat": ["chinese", "filipino", "thai", "vietnamese"],
"Sugar pie": ["american", "french", "canadian"],
"Steamed bun with vegetables": ["chinese", "taiwanese", "korean", "japanese"],
"Crystal chicken": ["chinese"],
"Buddha jumps over the wall": ["chinese"],
"Spareribs with brown sauce": ["chinese", "filipino", "thai"],
"Silky chicken roll": ["chinese", "vietnamese", "thai"],
"Fried rice with eel": ["japanese", "chinese"],
"Grilled cold noodles": ["chinese", "korean"],
"Cabbage tofu soup": ["chinese", "japanese", "korean", "vietnamese"],
"Northeast big lift": ["chinese"],  # Assumed translation of Dongbei-style mixed hotpot -gpt
"Grilled chiba tofu": ["chinese"],  # Chiba tofu is a Chinese specialty -gpt
"Fried konjac balls": ["japanese", "chinese", "korean"],
"Spike potatoes": ["chinese", "filipino", "thai"],  # Assumed crispy street-style skewered potatoes -gpt
"Hot and sour chicken feet": ["chinese", "filipino", "vietnamese"],
"Stir fried lily with celery": ["chinese"],
"Mango cake": ["filipino", "thai", "american", "french"],
"Japanese tofu with tin foil": ["japanese"],
"Corn pudding crispy": ["american", "filipino", "thai", "mexican"],
"Cold taro powder": ["chinese", "taiwanese", "filipino", "vietnamese"],
"Three fresh rice noodles": ["chinese", "vietnamese", "thai"],
"Rice cake": ["chinese", "japanese", "korean", "filipino", "indonesian"],
"Sauce cake": ["chinese", "vietnamese"],  # Possibly steamed savory rice cake -gpt
"Duck soup": ["chinese", "vietnamese", "french"],
"Duomang small meatballs": ["chinese"],  # Not widely known; assumed regional -gpt
"Fish ball soup": ["chinese", "filipino", "vietnamese", "thai"],
"Flour cake": ["chinese", "indian", "filipino", "iranian", "moroccan"],
"Walnut shortbread": ["british", "american", "french"],
"Corn pumpkin porridge": ["chinese", "filipino", "thai", "mexican", "ghanaian", "nigerian"],
"Shrimp and crab porridge": ["chinese", "thai", "filipino", "vietnamese"],
"Hot and sour cabbage": ["chinese", "korean", "vietnamese", "thai"],
"Brown sugar ice powder": ["chinese", "taiwanese"],
"Egg rice roll": ["chinese", "vietnamese"],
"Smoked sauce meat platter": ["chinese", "german", "czech", "american"],
"Pepper chicken": ["indian", "chinese", "nigerian", "sri_lankan"],
"Scrambled eggs with loofah": ["chinese", "vietnamese", "thai"],
"Stir fried pork and bone with chili": ["chinese", "filipino", "thai"],
"Corn grilled ribs": ["american", "filipino", "chinese", "mexican"],
"Roasted yellow throat": ["chinese"],  # Yellow croaker -gpt
"Barbecued pork": ["chinese", "filipino", "thai", "korean", "american"],
"Seaweed soup": ["japanese", "korean", "chinese"],
"Steamed pork": ["chinese", "filipino", "vietnamese"],
"Pineapple sweet and sour pork": ["chinese", "filipino", "thai"],
"Egg waffles": ["chinese"],  # Common in Hong Kong but mapped to Chinese -gpt
"Camphor tea duck": ["chinese"],
"Sausage rice": ["chinese", "filipino", "thai", "portuguese", "brazilian"],
"Mongolian roasted whole lamb": ["mongolian", "kazakhstani", "kirghiz", "chinese"],

}

print(len(food_to_cuisines))

cuisine_count = dict()
for food in food_to_cuisines.keys():
    for cuisine in food_to_cuisines[food]:
        if cuisine not in cuisine_count:
            cuisine_count[cuisine] = 1
        else:
            cuisine_count[cuisine] += 1
print(cuisine_count)

