food_to_cuisines = {
    "apple_pie": ["american"],
    "baby_back_ribs": ["american"],
    "baklava": ["albanian", "armenian", "azerbaijani", "cypriot", "greek", "iranian", "iraqi", "jordanian", "lebanese", "syrian", "turkish"],
    "beef_carpaccio": ["italian"],
    "beef_tartare": ["belgian", "french"],
    "beet_salad": ["russian", "polish", "ukrainian", "belarusian", "german"],
    "beignets": ["french", "american"],
    "bibimbap": ["south_korean"],
    "bread_pudding": ["british", "american"],
    "breakfast_burrito": ["american", "mexican"],
    "bruschetta": ["italian"],
    "caesar_salad": ["mexican", "american"],
    "cannoli": ["italian"],
    "caprese_salad": ["italian"],
    "carrot_cake": ["american", "british", "canadian"],
    "ceviche": ["peruvian", "ecuadorean", "mexican", "chilean", "colombian"],
    "cheese_plate": ["french", "swiss", "italian", "dutch"],
    "cheesecake": ["american", "german", "greek", "polish"],
    "chicken_curry": ["indian", "pakistani", "bangladeshi", "sri_lankan", "nepalese", "malaysian"],
    "chicken_quesadilla": ["mexican"],
    "chicken_wings": ["american"],
    "chocolate_cake": ["american", "german", "austrian", "swiss"],
    "chocolate_mousse": ["french"],
    "churros": ["spanish", "mexican", "portuguese"],
    "clam_chowder": ["american", "british"],
    "club_sandwich": ["american"],
    "crab_cakes": ["american"],
    "creme_brulee": ["french"],
    "croque_madame": ["french"],
    "cup_cakes": ["american"],
    "deviled_eggs": ["american", "british", "dutch"],
    "donuts": ["american", "dutch", "canadian"],
    "dumplings": ["chinese", "japanese", "korean", "mongolian", "nepalese", "russian", "polish", "ukrainian"],
    "edamame": ["japanese"],
    "eggs_benedict": ["american"],
    "escargots": ["french"],
    "falafel": ["egyptian", "israeli", "jordanian", "lebanese", "palestinian", "syrian", "yemeni"],
    "filet_mignon": ["french", "american"],
    "fish_and_chips": ["british", "australian", "new_zealander"],
    "foie_gras": ["french"],
    "french_fries": ["belgian", "french", "american"],
    "french_onion_soup": ["french"],
    "french_toast": ["french", "american"],
    "fried_calamari": ["italian", "greek", "spanish", "portuguese"],
    "fried_rice": ["chinese", "indonesian", "filipino", "thai", "vietnamese"],
    "frozen_yogurt": ["american", "greek"],
    "garlic_bread": ["italian", "american"],
    "gnocchi": ["italian"],
    "greek_salad": ["greek"],
    "grilled_cheese_sandwich": ["american", "british", "canadian"],
    "grilled_salmon": ["norwegian", "american", "canadian", "japanese"],
    "guacamole": ["mexican"],
    "gyoza": ["japanese", "chinese"],
    "hamburger": ["american", "german"],
    "hot_and_sour_soup": ["chinese"],
    "hot_dog": ["american", "german"],
    "huevos_rancheros": ["mexican"],
    "hummus": ["egyptian", "israeli", "jordanian", "lebanese", "palestinian", "syrian", "yemeni"],
    "ice_cream": ["american", "italian", "french", "turkish"],
    "lasagna": ["italian"],
    "lobster_bisque": ["french"],
    "lobster_roll_sandwich": ["american", "canadian"],
    "macaroni_and_cheese": ["american", "british"],
    "macarons": ["french"],
    "miso_soup": ["japanese"],
    "mussels": ["belgian", "french", "spanish", "dutch"],
    "nachos": ["mexican"],
    "omelette": ["french", "american"],
    "onion_rings": ["american"],
    "oysters": ["french", "american", "british", "australian"],
    "pad_thai": ["thai"],
    "paella": ["spanish"],
    "pancakes": ["american", "dutch", "british", "russian", "french"],
    "panna_cotta": ["italian"],
    "peking_duck": ["chinese"],
    "pho": ["vietnamese"],
    "pizza": ["italian", "american"],
    "pork_chop": ["american", "german", "austrian", "chinese"],
    "poutine": ["canadian"],
    "prime_rib": ["american", "british"],
    "pulled_pork_sandwich": ["american"],
    "ramen": ["japanese"],
    "ravioli": ["italian"],
    "red_velvet_cake": ["american"],
    "risotto": ["italian"],
    "samosa": ["indian", "pakistani", "nepalese", "bangladeshi"],
    "sashimi": ["japanese"],
    "scallops": ["french", "american", "japanese"],
    "seaweed_salad": ["japanese", "south_korean"],
    "shrimp_and_grits": ["american"],
    "spaghetti_bolognese": ["italian"],
    "spaghetti_carbonara": ["italian"],
    "spring_rolls": ["chinese", "vietnamese", "filipino", "thai"],
    "steak": ["american", "argentine", "brazilian", "australian", "british"],
    "strawberry_shortcake": ["american", "british"],
    "sushi": ["japanese"],
    "tacos": ["mexican"],
    "takoyaki": ["japanese"],
    "tiramisu": ["italian"],
    "tuna_tartare": ["french", "japanese", "american"],
    "waffles": ["belgian", "american"]
}

'''print(len(food_to_cuisines))

cuisine_count = dict()
for food in food_to_cuisines.keys():
    for cuisine in food_to_cuisines[food]:
        if cuisine not in cuisine_count:
            cuisine_count[cuisine] = 1
        else:
            cuisine_count[cuisine] += 1
print(cuisine_count)

cuisine_set = set()
for food in food_to_cuisines:
    for cuisine in food_to_cuisines[food]:
        if cuisine not in cuisine_set:
            cuisine_set.add(cuisine)

for cuisine in cuisine_set:
    print(cuisine)'''
